from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectField, DateField, IntegerField
from wtforms.validators import DataRequired,Length,Email,EqualTo,ValidationError, NumberRange, Regexp, Optional

class registrarAdmin(FlaskForm):
	clinica=SelectField('Clínica', choices=[('Odontologia','Odontología'),('Fisioterapia','Fisioterapia'),('Optometria','Optometría')])
	id=StringField('id', validators=[DataRequired(), Length(min=2,max=40)])
	nombre=StringField('Nombre', validators=[DataRequired(), Length(min=2,max=40)])
	correo=StringField('Correo electrónico', validators=[DataRequired(), Email(message='El correo electrónico no es valido'), Length(min=2,max=40)])
	username=StringField('Usuario', validators=[DataRequired(), Length(min=2,max=20)])
	password=PasswordField('Contraseña', validators=[DataRequired()])
	confirm_password=PasswordField('Confirmar contraseña', validators=[DataRequired(),EqualTo('password')])
	submit=SubmitField('Registrar Admin')

class registrarProfesor(FlaskForm):
	clinica=SelectField('Clínica', choices=[('Odontologia','Odontología'),('Fisioterapia','Fisioterapia'),('Optometria','Optometría')])
	rfc=StringField('rfc', validators=[DataRequired(), Length(min=2,max=40)])
	nombre=StringField('Nombre', validators=[DataRequired(), Length(min=2,max=40)])
	apellidos=StringField('Apellidos', validators=[DataRequired(), Length(min=2,max=40)])
	correo=StringField('Correo electrónico', validators=[DataRequired(), Email(message='El correo electrónico no es valido'), Length(min=2,max=40)])
	username=StringField('Usuario', validators=[DataRequired(), Length(min=2,max=40)])
	password=PasswordField('Contraseña', validators=[DataRequired()])
	confirm_password=PasswordField('Confirmar contraseña', validators=[DataRequired(),EqualTo('password')])
	submit=SubmitField('Registrar Profesor')

class registrarAlumno(FlaskForm):
	clinica=SelectField('Clínica', choices=[('Odontologia','Odontología'),('Fisioterapia','Fisioterapia'),('Optometria','Optometría')])
	numeroCuenta=StringField('Número de cuenta', validators=[DataRequired(), Length(min=2,max=30)])
	nombre=StringField('Nombre', validators=[DataRequired(), Length(min=2,max=30)])
	apellidos=StringField('Apellidos', validators=[DataRequired(), Length(min=2,max=40)])
	año=StringField('Año de ingreso', validators=[DataRequired(), Length(min=2,max=9)])
	asignatura=StringField('Asignatura', validators=[DataRequired(), Length(min=2,max=40)])
	correo=StringField('Correo electrónico', validators=[DataRequired(), Email(message='El correo electrónico no es valido'), Length(min=2,max=40)])
	username=StringField('Usuario', validators=[DataRequired(), Length(min=2,max=40)])
	password=PasswordField('Contraseña', validators=[DataRequired()])
	confirm_password=PasswordField('Confirmar contraseña', validators=[DataRequired(),EqualTo('password')])
	submit=SubmitField('Registrar Alumno')

class registrarPaciente(FlaskForm):
	id=StringField('id', validators=[DataRequired()])
	rfc=StringField('rfc', validators=[DataRequired(), Length(min=10, message='El RFC debe tener como mínimo 10 digitos')])
	fechaRemision=DateField('Fecha remisión', format='%Y-%m-%d', validators=[DataRequired()])
	fechaAtención=DateField('Fecha de atención', validators=[DataRequired()])
	sexo=SelectField('Sexo', choices=[('Masculino','Masculino'),('Femenino','Femenino')])
	edad=IntegerField('Edad', validators=[DataRequired(), NumberRange(min=0, max=110, message='La edad debe ser un número entre 0 y 110')])
	nombre=StringField('Nombre', validators=[DataRequired(), Length(min=2,max=40), Regexp('^[a-zA-Z	]', message='Debe empezar con una letra')])
	apellidoPaterno=StringField('Apellido paterno', validators=[DataRequired(), Length(min=2, max=40)])
	apellidoMaterno=StringField('Apellido materno', validators=[DataRequired(), Length(min=2, max=40)])
	fechaNacimiento=DateField('Fecha de nacimiento', validators=[DataRequired()])
	edadAños=IntegerField('Edad en años', validators=[DataRequired(), NumberRange(min=0, max=110, message='La edad en años debe ser un número entre 0 y 110')])
	edadMeses=IntegerField('Edad meses', validators=[DataRequired(), NumberRange(min=0, max=12, message='La edad en meses debe ser un número entre 0 y 12')])
	telefonoCasa=IntegerField('Teléfono casa', validators=[DataRequired(), NumberRange(min=1000000000, max=9999999999, message='El teléfono debe tener 10 números')])
	extensionTelefono=IntegerField('Extensión teléfono')
	telefonoOficina=IntegerField('Teléfono oficina', validators=[NumberRange(min=1000000000, max=9999999999, message='El teléfono debe tener 10 números')])
	celular=IntegerField('Celular', validators=[DataRequired(), NumberRange(min=1000000000, max=9999999999, message='El teléfono debe tener 10 números')])
	email=StringField('Email', validators=[DataRequired(), Email(message='El email no es valido')])
	calle=StringField('Calle', validators=[DataRequired()])
	numeroExterior=IntegerField('Número exterior', validators=[DataRequired()])
	numeroInterior=IntegerField('Número interior')
	colonia=StringField('Colonia', validators=[DataRequired()])
	ciudad=StringField('Ciudad', validators=[DataRequired()])
	codigoPostal=IntegerField('Código postal', validators=[DataRequired(), NumberRange(min=0, max=100000, message='El código postal debe ser número entre 0 y 100000')])
	estado=SelectField('Estado', choices=[('Aguascalientes','Aguascalientes'),('Baja California','Baja California'),('Baja California Sur','Baja California Sur'),('Campeche','Campeche'),('Chiapas','Chiapas'),('Chihuahua','Chihuahua'),('CDMX','CDMX'),('Coahuila','Coahuila'),('Colima','Colima'),('Durango','Durango'),('Estado de México','Estado de México'),('Guanajuato','Guanajuato'),('Guerrero','Guerrero'),('Hidalgo','Hidalgo'),('Jalisco','Jalisco'),('Michoacán','Michoacán'),('Morelos','Morelos'),('Nayarit','Nayarit'),('Nuevo León','Nuevo León'),('Oaxaca','Oaxaca'),('Puebla','Puebla'),('Querétaro','Querétaro'),('Quintana Roo','Quintana Roo'),('San Luis Potosí','San Luis Potosí'),('Sinaloa','Sinaloa'),('Sonora','Sonora'),('Tabasco','Tabasco'),('Tamaulipas','Tamaulipas'),('Tlaxcala','Tlaxcala'),('Veracruz','Veracruz'),('Yucatán','Yucatán'),('Zacatecas','Zacatecas'),('Otro','Otro')])
	pais=SelectField('País', choices=[('Afghanistan','Afghanistan'), ('Albania','Albania'), ('Alemania','Alemania'), ('Andorra','Andorra'), ('Angola','Angola'), ('Anguila','Anguila'), ('Antártida','Antártida'), ('Antigua y Barbuda','Antigua y Barbuda'), ('Arabia Saudita','Arabia Saudita'), ('Argelia','Argelia'), ('Argentina','Argentina'), ('Armenia','Armenia'), ('Aruba','Aruba'), ('Australia','Australia'), ('Austria','Austria'), ('Azerbaiyán','Azerbaiyán'), ('Bahamas','Bahamas'), ('Bahrein','Bahrein'), ('Bangladesh','Bangladesh'), ('Barbados','Barbados'), ('Bélgica','Bélgica'), ('Belice','Belice'), ('Benín','Benín'), ('Bhután','Bhután'), ('Bielorrusia','Bielorrusia'), ('Birmania','Birmania'), ('Bolivia','Bolivia'), ('Bosnia y Herzegovina','Bosnia y Herzegovina'), ('Botsuana','Botsuana'), ('Brasil','Brasil'), ('Brunéi','Brunéi'), ('Bulgaria','Bulgaria'), ('Burkina Faso','Burkina Faso'), ('Burundi','Burundi'), ('Cabo Verde','Cabo Verde'), ('Camboya','Camboya'), ('Camerún','Camerún'), ('Canadá','Canadá'), ('Chad','Chad'), ('Chile','Chile'), ('China','China'), ('Chipre','Chipre'), ('Ciudad del Vaticano','Ciudad del Vaticano'), ('Colombia','Colombia'), ('Comoras','Comoras'),  ('Corea del Norte','Corea del Norte'), ('Corea del Sur','Corea del Sur'), ('Costa de Marfil','Costa de Marfil'), ('Costa Rica','Costa Rica'), ('Croacia','Croacia'), ('Cuba','Cuba'), ('Curazao','Curazao'), ('Dinamarca','Dinamarca'), ('Dominica','Dominica'), ('Ecuador','Ecuador'), ('Egipto','Egipto'), ('El Salvador','El Salvador'), ('Emiratos Árabes Unidos','Emiratos Árabes Unidos'), ('Eritrea','Eritrea'), ('Eslovaquia','Eslovaquia'), ('Eslovenia','Eslovenia'), ('España','España'), ('Estados Unidos de América','Estados Unidos de América'), ('Estonia','Estonia'), ('Etiopía','Etiopía'), ('Filipinas','Filipinas'), ('Finlandia','Finlandia'), ('Fiyi','Fiyi'), ('Francia','Francia'), ('Gabón','Gabón'), ('Gambia','Gambia'), ('Georgia','Georgia'), ('Ghana','Ghana'), ('Gibraltar','Gibraltar'), ('Granada','Granada'), ('Grecia','Grecia'), ('Groenlandia','Groenlandia'), ('Guadalupe','Guadalupe'), ('Guam','Guam'), ('Guatemala','Guatemala'), ('Guayana Francesa','Guayana Francesa'), ('Guernsey','Guernsey'), ('Guinea','Guinea'), ('Guinea Ecuatorial','Guinea Ecuatorial'), ('Guinea-Bissau','Guinea-Bissau'), ('Guyana','Guyana'), ('Haití','Haití'), ('Honduras','Honduras'), ('Hong kong','Hong kong'), ('Hungría','Hungría'), ('India','India'), ('Indonesia','Indonesia'), ('Irak','Irak'), ('Irán','Irán'), ('Irlanda','Irlanda'), ('Isla Bouvet','Isla Bouvet'), ('Isla de Man','Isla de Man'), ('Isla de Navidad','Isla de Navidad'), ('Isla Norfolk','Isla Norfolk'), ('Islandia','Islandia'), ('Islas Bermudas','Islas Bermudas'), ('Islas Caimán','Islas Caimán'), ('Islas Cocos (Keeling)','Islas Cocos (Keeling)'), ('Islas Cook','Islas Cook'), ('Islas de Åland','Islas de Åland'), ('Islas Feroe','Islas Feroe'), ('Islas Georgias del Sur y Sandwich del Sur','Islas Georgias del Sur y Sandwich del Sur'), ('Islas Heard y McDonald','Islas Heard y McDonald'), ('Islas Maldivas','Islas Maldivas'), ('Islas Malvinas','Islas Malvinas'), ('Islas Marianas del Norte','Islas Marianas del Norte'), ('Islas Marshall','Islas Marshall'), ('Islas Pitcairn','Islas Pitcairn'), ('Islas Salomón','Islas Salomón'), ('Islas Turcas y Caicos','Islas Turcas y Caicos'), ('Islas Ultramarinas Menores de Estados Unidos','Islas Ultramarinas Menores de Estados Unidos'), ('Islas Vírgenes Británicas','Islas Vírgenes Británicas'), ('Islas Vírgenes de los Estados Unidos','Islas Vírgenes de los Estados Unidos'), ('Israel','Israel'), ('Italia','Italia'), ('Jamaica','Jamaica'), ('Japón','Japón'), ('Jersey','Jersey'), ('Jordania','Jordania'), ('Kazajistán','Kazajistán'), ('Kenia','Kenia'), ('Kirguistán','Kirguistán'), ('Kiribati','Kiribati'), ('Kuwait','Kuwait'), ('Laos','Laos'), ('Lesoto','Lesoto'), ('Letonia','Letonia'), ('Líbano','Líbano'), ('Liberia','Liberia'), ('Libia','Libia'), ('Liechtenstein','Liechtenstein'), ('Lituania','Lituania'), ('Luxemburgo','Luxemburgo'), ('Macao','Macao'), ('Macedonia','Macedonia'), ('Madagascar','Madagascar'), ('Malasia','Malasia'), ('Malawi','Malawi'), ('Mali','Mali'), ('Malta','Malta'), ('Marruecos','Marruecos'), ('Martinica','Martinica'), ('Mauricio','Mauricio'), ('Mauritania','Mauritania'), ('Mayotte','Mayotte'), ('México','México'), ('Micronesia','Micronesia'), ('Moldavia','Moldavia'), ('Mónaco','Mónaco'), ('Mongolia','Mongolia'), ('Montenegro','Montenegro'), ('Montserrat','Montserrat'), ('Mozambique','Mozambique'), ('Namibia','Namibia'), ('Nauru','Nauru'), ('Nepal','Nepal'), ('Nicaragua','Nicaragua'), ('Niger','Niger'), ('Nigeria','Nigeria'), ('Niue','Niue'), ('Noruega','Noruega'), ('Nueva Caledonia','Nueva Caledonia'), ('Nueva Zelanda','Nueva Zelanda'), ('Omán','Omán'), ('Países Bajos','Países Bajos'), ('Pakistán','Pakistán'), ('Palau','Palau'), ('Palestina','Palestina'), ('Panamá','Panamá'), ('Papúa Nueva Guinea','Papúa Nueva Guinea'), ('Paraguay','Paraguay'), ('Perú','Perú'), ('Polinesia Francesa','Polinesia Francesa'), ('Polonia','Polonia'), ('Portugal','Portugal'), ('Puerto Rico','Puerto Rico'), ('Qatar','Qatar'), ('Reino Unido','Reino Unido'), ('República Centroafricana','República Centroafricana'), ('República Checa','República Checa'), ('República del Congo','República del Congo'), ('República Democrática del Congo','República Democrática del Congo'), ('República Dominicana','República Dominicana'), ('República de Sudán del Sur','República de Sudán del Sur'), ('Reunión','Reunión'), ('Ruanda','Ruanda'), ('Rumanía','Rumanía'), ('Rusia','Rusia'), ('Sahara Occidental','Sahara Occidental'), ('Samoa','Samoa'), ('Samoa Americana','Samoa Americana'), ('San Bartolomé','San Bartolomé'), ('San Cristóbal y Nieves','San Cristóbal y Nieves'), ('San Marino','San Marino'), ('San Martín (Francia)','San Martín (Francia)'), ('San Pedro y Miquelón','San Pedro y Miquelón'), ('San Vicente y las Granadinas','San Vicente y las Granadinas'), ('Santa Elena','Santa Elena'), ('Santa Lucía','Santa Lucía'), ('Santo Tomé y Príncipe','Santo Tomé y Príncipe'), ('Senegal','Senegal'), ('Serbia','Serbia'), ('Seychelles','Seychelles'), ('Sierra Leona','Sierra Leona'), ('Singapur','Singapur'), ('Sint Maarten','Sint Maarten'), ('Siria','Siria'), ('Somalia','Somalia'), ('Sri lanka','Sri lanka'), ('Sudáfrica','Sudáfrica'), ('Sudán','Sudán'), ('Suecia','Suecia'), ('Suiza','Suiza'), ('Surinám','Surinám'), ('Svalbard y Jan Mayen','Svalbard y Jan Mayen'), ('Swazilandia','Swazilandia'), ('Tayikistán','Tayikistán'), ('Tailandia','Tailandia'), ('Taiwán','Taiwán'), ('Tanzania','Tanzania'), ('Territorio Británico del Océano Índico','Territorio Británico del Océano Índico'), ('Territorios Australes y Antárticas Franceses','Territorios Australes y Antárticas Franceses'), ('Timor Oriental','Timor Oriental'), ('Togo','Togo'), ('Tokelau','Tokelau'), ('Tonga','Tonga'), ('Trinidad y Tobago','Trinidad y Tobago'), ('Tunez','Tunez'), ('Turkmenistán','Turkmenistán'), ('Turquía','Turquía'), ('Tuvalu','Tuvalu'), ('Ucrania','Ucrania'), ('Uganda','Uganda'), ('Uruguay','Uruguay'), ('Uzbekistán','Uzbekistán'), ('Vanuatu','Vanuatu'), ('Venezuela','Venezuela'), ('Vietnam','Vietnam'), ('Wallis y Futuna','Wallis y Futuna'), ('Yemen','Yemen'), ('Yibuti','Yibuti'), ('Zambia','Zambia'), ('Zimbabue','Zimbabue')])
	origen=StringField('Origen', validators=[DataRequired()])
	estadoCivil=SelectField('Estado civil', choices=[('Soltero/a','Soltero/a'),('Casado/a','Casado/a'),('Divorciado/a','Divorciado/a'), ('Viudo/a','Viudo/a')])
	ocupacion=SelectField('Ocupación', choices=[('Estudiante','Estudiante'),('Trabajador','Trabajador'),('Jubilado','Jubilado'),('Otro','Otro')])
	nacionalidad=StringField('Nacionalidad', validators=[DataRequired()])
	tipoSangre=SelectField('Tipo de sangre', choices=[('A+','A+'),('A-','A-'),('B+','B+'),('B-','B-'),('AB+','AB+'),('AB-','AB-'),('O+','O+'),('O-','O-'),('Desconocido','Desconocido')])
	clasificacion=StringField('Clasificación', validators=[DataRequired()])
	alertaAdministrativa=StringField('Alerta administrativa')
	numeroSeguro=StringField('Numero seguro')
	nombreContactoEmergencia=StringField('Nombre contacto emergencia', validators=[DataRequired()])
	telefonoContactoEmergencia=IntegerField('Teléfono contacto emergencia', validators=[DataRequired(), NumberRange(min=1000000000, max=9999999999, message='El teléfono debe tener 10 números')])
	coberturaMedica=SelectField('Cobertura Médica', choices=[('Si','Si'),('No','No')])
	relacionContactoPaciente=SelectField('Relación del contacto con el paciente', choices=[('Madre','Madre'),('Padre','Padre'),('Hijo/a','Hijo/a'),('Esposo/a','Esposo/a'),('Tío/a','Tío/a'), ('Otro','Otro')])
	submit=SubmitField('Registrar Paciente')

class consulta(FlaskForm):
	clinica=SelectField('Clínica', choices=[('Odontologia','Odontología'),('Fisioterapia','Fisioterapia'),('Optometria','Optometría')])
	personal=SelectField('Personal', choices=[('admin','Admin'),('profesor','Profesor'),('alumno','Alumno')])
	submit=SubmitField('Consulta')

class consultaPacientes(FlaskForm):
	idPaciente=StringField('Por id')
	submitIdPaciente=SubmitField('Consultar')
	nombrePaciente=StringField('Por nombre')
	submitNombrePaciente=SubmitField('Consultar')

class optometria(FlaskForm):
	octDiscoOptico=FileField('OCT disco óptico (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	octMacular=FileField('OCT macular  200 x 200 (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	octMacularCube=FileField('OCT macular cube  (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	octA=FileField('OCT-A (Angio-OCT) Montage 8x8 (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	anguloIridocorneal=FileField('Ángulo iridocorneal (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	retinografiaPosiciones=FileField('Retinografía 9 posiciones (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	retinografiaCentral=FileField('Retinografía central (PDF y/o TIFF)', validators=[FileAllowed(['pdf','tiff'])])
	ergBasal=FileField('ERG Basal (PDF y rff)', validators=[FileAllowed(['pdf','rff'])])
	ergPhNR=FileField('ERG PhNR (PDF y rff)', validators=[FileAllowed(['pdf','rff'])])
	ergRD=FileField('ERG RD (PDF y rff)', validators=[FileAllowed(['pdf','rff'])])
	ergFlickerThenFlash=FileField('ERG Flicker then Flash (PDF y rff)', validators=[FileAllowed(['pdf','rff'])])
	contrastSensitivity=StringField('Contrast sensitivity')  
	tonometria=StringField('Tonometría (GAT) - mmHg')
	campimetriaFast=FileField('Campimetría Fast (PDF)', validators=[FileAllowed(['pdf'])])
	topografia=FileField('Topografía (PDF)', validators=[FileAllowed(['pdf'])])
	estudiosClinicos=FileField('Estudios Clínicos-PDF', validators=[FileAllowed(['pdf'])])
	OSDI=StringField('OSDI-Puntaje')
	BUT=StringField('BUT-segundos')
	schirmer=StringField('Schirmer-mm')
	pesoCorporal=StringField('Peso corporal-Kgs')
	estatura=StringField('Estatura-cm')
	circunferenciaCintura=StringField('Circunferencia de cintura - cm')
	IMC=StringField('IMC - kg/m2')
	genero=StringField('Género  - Masculino/femenino')
	edad=StringField('Edad-Años y meses')
	paquimetria=StringField('Paquimetría-micras')
	glucosa=StringField('Glucosa - mg/dl')
	presiónArterial=StringField('Presión arterial - mmHg')
	diagnosticoOcular=StringField('Diagnóstico ocular')
	tratamientos=StringField('Tratamientos')
	seguimiento=StringField('Seguimiento')
	proximaVisita=DateField('Próxima visita', validators=[Optional()])
	submit=SubmitField('Guardar información')


class odontologia(FlaskForm):
	octDiscoOptico=FileField('OCT disco óptico (PDF y/o TIFF)')
	octMacular=StringField('OCT macular  200 x 200 (PDF y/o TIFF)')
	octMacularCube=StringField('OCT macular cube  (PDF y/o TIFF)')
	octA=StringField('OCT-A (Angio-OCT) Montage 8x8 (PDF y/o TIFF)')
	anguloIridocorneal=StringField('Ángulo iridocorneal (PDF y/o TIFF)')
	proximaVisita=DateField('Próxima visita', validators=[Optional()])
	submit=SubmitField('Guardar información')

class fisioterapia(FlaskForm):
	octDiscoOptico=FileField('OCT disco óptico (PDF y/o TIFF)')
	octMacular=StringField('OCT macular  200 x 200 (PDF y/o TIFF)')
	octMacularCube=StringField('OCT macular cube  (PDF y/o TIFF)')
	octA=StringField('OCT-A (Angio-OCT) Montage 8x8 (PDF y/o TIFF)')
	anguloIridocorneal=StringField('Ángulo iridocorneal (PDF y/o TIFF)')
	proximaVisita=DateField('Próxima visita', validators=[Optional()])
	submit=SubmitField('Guardar información')

class LoginForm(FlaskForm):
	username=StringField('Usuario', validators=[DataRequired(), Length(min=2,max=20)])
	password=PasswordField('Password',validators=[DataRequired()])
	remember=BooleanField('Recordarme')
	submit=SubmitField('Iniciar Sesion')

class RecuperarForm(FlaskForm):
	correo=StringField('Correo electrónico', validators=[DataRequired(), Email(message='El correo electrónico no es valido')])
	submit=SubmitField('Recuperar')

class CambiarForm(FlaskForm):
	password=PasswordField('Password',validators=[DataRequired()])
	confirmPassword=PasswordField('Confirmar contraseña', validators=[DataRequired(),EqualTo('password')])
	submit=SubmitField('Cambiar contraseña')